### ISSUE TITLE
Which IDE used ?

### ISSUE THREAD

**Issue by Borel-Kamnang** [tuupola/hagl#107]
hello, please can i know whict i the best IDE recommanded to program a RPI PICO or PICO W
And on wich IDE can i easily use this librairies ?

**Comment by tuupola** [comment]
I do not use any IDE. For editor I use [VSCodium](https://vscodium.com/) and for everything else the commandline. HAGL itself does not require anything special. You can use whatever tools you normally use. With RPI Pico the tricky part first is the `CMakeLists.txt` file.

To use HAGL with RPI Pico you need to get both the main library and the HAL.

```
$ mkdir external
$ cd external
$ git submodule add https://github.com/tuupola/hagl_pico_mipi.git hagl_hal
$ git submodule add https://github.com/tuupola/hagl.git
```

Then in your `CMakeLists.txt` include both libraries in the build.

```
add_subdirectory(external/hagl)
add_subdirectory(external/hagl_hal)
target_link_libraries(firmware hagl hagl_hal)
```

Last thing to do is to configure the HAL. Easiest is to use any of the ready made [config files](https://github.com/tuupola/hagl_pico_mipi/tree/master/cmake). For example:

```
include("external/hagl_hal/cmake/waveshare-rp2040-lcd-096.cmake")
```

If you have some other board or display you need to [configure manually](https://github.com/tuupola/hagl_pico_mipi#configuration).
