### ISSUE TITLE
Full list of supported displays/chips

### ISSUE THREAD

**Issue by UncleRus** [tuupola/hagl#40]
Awesome library, love it!

Could you provide a complete list of existing drivers with the names of the supported controllers?
For example, I have a display based on ST7789 and before I write a driver for HAGL for this chip on ESP32, it would be very convenient to look at the list and check if someone has already written it.

**Comment by tuupola** [comment]
ST7889 is a standard [MIPI DCS](https://www.mipi.org/specifications/display-command-set) chip so it is covered by [ESP32 MIPI DCS HAL](https://github.com/tuupola/hagl_esp_mipi). Most of ST and ILI display driver chips follow this standard. You just need to set the display dimensions and orientation via menuconfig. I have personally tested ST7735S, ST7789V, ST7789V2, ILI9341 and ILI9163. 

In other words if you have an ST or ILI display it probably is already supported. There might be some older obscure ST and ILI chips which are not supported. Have not been able to find any though.

I recently started to work with [HAL for Solomon displays](https://github.com/tuupola/hagl_esp_solomon). They do not seem to follow any standard. Even the different SSD chips have totally different command sets between themselves. I was able to hack together working support for SSD1351 but this code is far from ready.

If you have any Solomon displays they would be a good candidate.

As I side note you might have noticed I include only the [mandatory initialisation sequence](https://github.com/tuupola/hagl_esp_mipi/blob/f6b39d7e671732a17ffeffbee39ab910ab0f8eda/src/mipi_display.c#L222-L242) for the chips. Most drivers you see in the wild also include stuff like power settings and gamma curves. Those have nothing to do with the driver chip itself. They are specific for the display panel which is attached to the chip. People just keep copying them from some other display driver without realising this.

Below is a list of all the HAL's I have made so far:

https://github.com/tuupola/hagl_esp_mipi
https://github.com/tuupola/hagl_esp_solomon
https://github.com/tuupola/hagl_gd32v_mipi
https://github.com/tuupola/hagl_pico_mipi
https://github.com/tuupola/hagl_sdl2
https://github.com/tuupola/hagl_gd

**Comment by UncleRus** [comment]
Thank you!
