### ISSUE TITLE
DISPLAY_DEPTH < 8

### ISSUE THREAD

**Issue by UncleRus** [tuupola/hagl#47]
How do I write a driver that works with bitmap_t for a 4-bit color display controller?
As far as I can see, bitmap_t does not correctly support DISPLAY_DEPTH < 8 bits.

**Comment by tuupola** [comment]
I have not thought about supporting anything else than multiples of 8 bits yet. This is mostly to keep things simple. Not sure how much 4 bit bitmaps would complicate the code. That said if amount of memory is not a problem then as a workaround even if HAGL internally used 8 bits the HAL could convert the 8 bit colours on the fly to 4 bits before sending them to display.

Which display are you working on btw?

**Comment by UncleRus** [comment]
SSD1322 - 128x64 4-bit grayscale OLED controller
