### ISSUE TITLE
Input API?

### ISSUE THREAD

**Issue by RobLoach** [tuupola/hagl#80]
Abstracting the way input is handled within the Backend will mean an easy way to implement different HAGL applications and allow running able them across different backends.

Is this something that you've been considering? Maybe like a keystate() or input() callback or something to set the input state across input devices.

**Comment by tuupola** [comment]
Not considering since HAGL is a graphics library not a general purpose library. I remember seeing hardware agnostic input libraries but I do not remember their names anymore though.

**Comment by RobLoach** [comment]
Thanks! Love where this is going and really excited to see it grow.

**Comment by tuupola** [comment]
Now when you said it a hardware agnostic input library is really good idea for an open source project. I do remember seeing one at some point. I have no idea what the name was.

**Comment by CHiPs44** [comment]
HAIL?

**Comment by tuupola** [comment]
There is two I have been pondering to test for a while. Quickly glancing I like the way they look and how api is structured. 

https://github.com/rxi/microui
https://github.com/abhra0897/LameUI

**Comment by tuupola** [comment]
Ah sorry I misread. I thought you meant UI but it was about input devices.
